### ISSUE TITLE
Add rss feed

### ISSUE THREAD

**Issue by n1rjal** [UTSAVS26/Personalized-News-Aggregator#2]
Rss feeds are feeds that powers google home page like features where you will see all the various news aggregated. Here is an example of a RSS feed from cnn.com

[Example RSS Feed](http://rss.cnn.com/rss/cnn_topstories.rss)

We will make a system that will use this feed and summarize it. 

Steps:
1. Make a celery based background task that will fetch the rss feed
2. Parse it, summarize it, save it in db

**Comment by UTSAVS26** [comment]
@n1rjal you can now continue your work on rrs feed.

**Comment by UTSAVS26** [comment]
@n1rjal you have closed the issue?

**Comment by n1rjal** [comment]
Yes I am goimg to raise another, the server is not working properly. Its says app error in main

**Comment by UTSAVS26** [comment]
> Yes I am goimg to raise another, the server is not working properly. Its says app error in main

Okie
